export const data = [
  {
    id: 1,
    title: 'Científicos desarrollan un nuevo material superconductor a temperatura ambiente, revolucionando la transmisión de energía y la electrónica',
    description: 'Este avance podría reducir drásticamente las pérdidas de energía en las redes eléctricas y permitir el desarrollo de dispositivos electrónicos más eficientes',
    url: 'www.revistacientifica.com/articulo01',
    date: '2024-12-01',
  },
  {
    id: 2,
    title: 'El uso de CRISPR para editar genes en embriones humanos plantea dilemas éticos y científicos',
    description: 'Investigadores debaten sobre las implicaciones de modificar el ADN humano para prevenir enfermedades hereditarias y mejorar características físicas',
    url: 'www.revistacientifica.com/articulo12',
    date: '2024-12-02',
  },
  {
    id: 3,
    title: 'Nuevas técnicas de imagen cerebral revelan cómo se forman los recuerdos a nivel neuronal',
    description: 'Utilizando avanzadas tecnologías de resonancia magnética, los científicos han podido observar la creación y almacenamiento de recuerdos en tiempo real',
    url: 'www.revistacientifica.com/articulo13',
    date: '2024-12-03',
  },
  {
    id: 4,
    title: 'Descubren un método para convertir el dióxido de carbono en combustible limpio',
    description: 'Este proceso innovador podría ayudar a reducir las emisiones de gases de efecto invernadero y proporcionar una fuente de energía sostenible',
    url: 'www.revistacientifica.com/articulo14',
    date: '2024-12-04',
  },
  {
    id: 5,
    title: 'La inteligencia artificial supera a los médicos en el diagnóstico de enfermedades raras',
    description: 'Un nuevo algoritmo de IA ha demostrado ser más preciso y rápido que los especialistas humanos en la identificación de patologías poco comunes',
    url: 'www.revistacientifica.com/articulo15',
    date: '2024-12-05',
  },
  {
    id: 6,
    title: 'El impacto de los microplásticos en la salud humana: un estudio alarmante',
    description: 'Investigaciones recientes han encontrado microplásticos en órganos humanos, lo que plantea serias preocupaciones sobre sus efectos a largo plazo',
    url: 'www.revistacientifica.com/articulo16',
    date: '2024-12-06',
  },
  {
    id: 7,
    title: 'Nuevas vacunas de ARNm muestran eficacia contra múltiples variantes del virus de la gripe',
    description: 'Estas vacunas innovadoras podrían ofrecer una protección más amplia y duradera contra las cepas emergentes de la gripe',
    url: 'www.revistacientifica.com/articulo17',
    date: '2024-12-07',
  },
  {
    id: 8,
    title: 'El papel de la microbiota intestinal en la prevención de enfermedades crónicas',
    description: 'Estudios recientes sugieren que una flora intestinal saludable puede ser clave para prevenir afecciones como la diabetes y las enfermedades cardíacas',
    url: 'www.revistacientifica.com/articulo18',
    date: '2024-12-08',
  },
  {
    id: 9,
    title: 'Desarrollan un exoesqueleto robótico que permite a personas con parálisis caminar de nuevo',
    description: 'Este dispositivo avanzado utiliza sensores y motores para replicar el movimiento natural de las piernas, ofreciendo una nueva esperanza a los pacientes',
    url: 'www.revistacientifica.com/articulo19',
    date: '2024-12-09',
  },
  {
    id: 10,
    title: 'La exploración de los océanos profundos revela nuevas especies y ecosistemas desconocidos',
    description: 'Utilizando submarinos no tripulados, los científicos han descubierto una gran diversidad de vida en las profundidades marinas',
    url: 'www.revistacientifica.com/articulo20',
    date: '2024-12-10',
  },
  {
    id: 11,
    title: 'Científicos desarrollan una vacuna universal contra el cáncer basada en células T modificadas genéticamente',
    description: 'Esta vacuna ha mostrado resultados prometedores en ensayos clínicos, atacando diversos tipos de cáncer con alta eficacia',
    url: 'www.revistacientifica.com/articulo21',
    date: '2024-12-01',
  },
  {
    id: 12,
    title: 'El uso de drones en la agricultura mejora la eficiencia y reduce el uso de pesticidas',
    description: 'Los drones equipados con sensores avanzados permiten un monitoreo preciso de los cultivos y una aplicación más eficiente de insumos agrícolas',
    url: 'www.revistacientifica.com/articulo22',
    date: '2024-12-11',
  },
  {
    id: 13,
    title: 'Descubren una nueva técnica para reciclar plásticos que reduce significativamente la contaminación',
    description: 'Este método innovador convierte los plásticos desechados en materiales reutilizables de alta calidad',
    url: 'www.revistacientifica.com/articulo23',
    date: '2024-12-13',
  },
  {
    id: 14,
    title: 'La inteligencia artificial en la predicción de terremotos: avances y desafíos',
    description: 'Investigadores están utilizando algoritmos de IA para analizar patrones sísmicos y mejorar la precisión de las predicciones de terremotos',
    url: 'www.revistacientifica.com/articulo24',
    date: '2024-12-14',
  },
  {
    id: 15,
    title: 'Nuevos tratamientos para enfermedades neurodegenerativas basados en la terapia génica',
    description: 'Estos tratamientos prometen ralentizar la progresión de enfermedades como el Alzheimer y el Parkinson',
    url: 'www.revistacientifica.com/articulo25',
    date: '2024-12-15',
  },
  {
    id: 16,
    title: 'El impacto de la contaminación lumínica en la biodiversidad nocturna',
    description: 'Un estudio revela cómo la luz artificial afecta a los ecosistemas y propone soluciones para mitigar sus efectos negativos',
    url: 'www.revistacientifica.com/articulo26',
    date: '2024-12-16',
  },
  {
    id: 17,
    title: 'Desarrollan una nueva técnica de edición genética para corregir mutaciones en embriones humanos',
    description: 'Esta técnica podría prevenir enfermedades genéticas hereditarias antes del nacimiento',
    url: 'www.revistacientifica.com/articulo27',
    date: '2024-12-17',
  },
  {
    id: 18,
    title: 'El uso de materiales biodegradables en la construcción: una solución sostenible',
    description: 'Investigadores están desarrollando materiales de construcción que se descomponen de manera segura en el medio ambiente',
    url: 'www.revistacientifica.com/articulo28',
    date: '2024-12-18',
  },
  {
    id: 19,
    title: 'La exploración de la Luna: nuevos descubrimientos sobre su geología y recursos',
    description: 'Misiones recientes han revelado información crucial sobre la composición y los recursos disponibles en la Luna',
    url: 'www.revistacientifica.com/articulo29',
    date: '2024-12-19',
  },
  {
    id: 20,
    title: 'El papel de la nanotecnología en el desarrollo de nuevos tratamientos médicos',
    description: 'La nanotecnología está permitiendo la creación de terapias más precisas y efectivas para una variedad de enfermedades',
    url: 'www.revistacientifica.com/articulo30',
    date: '2024-12-20',
  },
  {
    id: 21,
    title: 'Científicos desarrollan una nueva técnica para la detección temprana del cáncer mediante análisis de sangre',
    description: 'Esta técnica no invasiva podría revolucionar la forma en que se diagnostican y tratan los cánceres en sus etapas iniciales',
    url: 'www.revistacientifica.com/articulo31',
    date: '2024-12-21',
  },
  {
    id: 22,
    title: 'El impacto del cambio climático en la migración de aves: un estudio a largo plazo',
    description: 'Investigadores han observado cambios significativos en los patrones migratorios de diversas especies de aves debido al calentamiento global',
    url: 'www.revistacientifica.com/articulo32',
    date: '2024-12-22',
  },
  {
    id: 23,
    title: 'Nuevas terapias basadas en células madre muestran resultados prometedores en la regeneración de tejidos',
    description: 'Estos tratamientos podrían ofrecer soluciones para lesiones y enfermedades que actualmente no tienen cura',
    url: 'www.revistacientifica.com/articulo33',
    date: '2024-12-23',
  },
  {
    id: 24,
    title: 'El uso de inteligencia artificial en la predicción de epidemias: un enfoque innovador',
    description: 'Algoritmos avanzados están ayudando a predecir y controlar la propagación de enfermedades infecciosas a nivel global',
    url: 'www.revistacientifica.com/articulo34',
    date: '2024-12-24',
  },
  {
    id: 25,
    title: 'Descubren un nuevo compuesto químico que podría revolucionar el tratamiento de enfermedades neurodegenerativas',
    description: 'Este compuesto ha mostrado potencial para proteger y regenerar neuronas dañadas',
    url: 'www.revistacientifica.com/articulo35',
    date: '2024-12-25',
  },
  {
    id: 26,
    title: 'La exploración de Marte: nuevos hallazgos sobre la posibilidad de vida pasada en el planeta rojo',
    description: 'Misiones recientes han encontrado indicios de agua líquida y compuestos orgánicos en Marte',
    url: 'www.revistacientifica.com/articulo36',
    date: '2024-12-26',
  },
  {
    id: 27,
    title: 'El papel de la genética en la longevidad: un estudio revela los secretos de los centenarios',
    description: 'Investigadores han identificado genes específicos que podrían estar relacionados con una vida más larga y saludable',
    url: 'www.revistacientifica.com/articulo37',
    date: '2024-12-27',
  },
  {
    id: 28,
    title: 'Nuevas tecnologías para la purificación del agua: soluciones innovadoras para la crisis hídrica global',
    description: 'Estos avances prometen proporcionar agua potable a comunidades que actualmente carecen de acceso a recursos seguros',
    url: 'www.revistacientifica.com/articulo38',
    date: '2024-12-28',
  },
  {
    id: 29,
    title: 'El impacto de la contaminación del aire en la salud mental: un estudio alarmante',
    description: 'Investigaciones recientes sugieren que la exposición a largo plazo a contaminantes del aire puede estar relacionada con un aumento en los trastornos mentales',
    url: 'www.revistacientifica.com/articulo39',
    date: '2024-12-29',
  },
  {
    id: 30,
    title: 'Desarrollan una nueva técnica de cultivo celular que podría acelerar la investigación biomédica',
    description: 'Esta técnica permite el crecimiento más rápido y eficiente de células en laboratorio, facilitando el estudio de enfermedades y el desarrollo de tratamientos',
    url: 'www.revistacientifica.com/articulo40',
    date: '2024-12-30',
  },
  {
    id: 31,
    title: 'Científicos desarrollan una nueva técnica para la regeneración de órganos utilizando células madre pluripotentes',
    description: 'Esta técnica podría revolucionar los trasplantes de órganos, permitiendo la regeneración de tejidos dañados a partir de las propias células del paciente',
    url: 'www.revistacientifica.com/articulo41',
    date: '2024-12-31',
  },
  {
    id: 32,
    title: 'El impacto de los microplásticos en los océanos: un estudio revela la magnitud del problema',
    description: 'Investigadores han encontrado microplásticos en todos los niveles de la cadena alimentaria marina, desde el plancton hasta los grandes depredadores',
    url: 'www.revistacientifica.com/articulo42',
    date: '2025-01-01',
  },
  {
    id: 33,
    title: 'Nuevas terapias génicas muestran eficacia en el tratamiento de enfermedades hereditarias',
    description: 'Estas terapias están diseñadas para corregir mutaciones genéticas específicas, ofreciendo esperanza a pacientes con enfermedades raras',
    url: 'www.revistacientifica.com/articulo43',
    date: '2025-01-02',
  },
  {
    id: 34,
    title: 'El uso de la realidad virtual en la rehabilitación física: un enfoque innovador',
    description: 'La realidad virtual está siendo utilizada para crear entornos inmersivos que ayudan a los pacientes a recuperar la movilidad y la fuerza',
    url: 'www.revistacientifica.com/articulo44',
    date: '2025-01-03',
  },
  {
    id: 35,
    title: 'Descubren un nuevo mecanismo de resistencia a los antibióticos en bacterias patógenas',
    description: 'Este hallazgo podría conducir al desarrollo de nuevos tratamientos para combatir infecciones resistentes a los medicamentos actuales',
    url: 'www.revistacientifica.com/articulo45',
    date: '2025-01-04',
  },
  {
    id: 36,
    title: 'El impacto del cambio climático en la biodiversidad terrestre: un estudio global',
    description: 'Investigadores han documentado cómo el calentamiento global está afectando a diversas especies y ecosistemas en todo el mundo',
    url: 'www.revistacientifica.com/articulo46',
    date: '2025-01-05',
  },
  {
    id: 37,
    title: 'Nuevas tecnologías para la captura y almacenamiento de carbono: una solución para el cambio climático',
    description: 'Estas tecnologías están diseñadas para reducir las emisiones de CO2 y mitigar los efectos del calentamiento global',
    url: 'www.revistacientifica.com/articulo47',
    date: '2025-01-06',
  },
  {
    id: 38,
    title: 'El uso de la inteligencia artificial en la detección temprana de enfermedades cardíacas',
    description: 'Algoritmos avanzados están siendo utilizados para analizar datos médicos y predecir el riesgo de enfermedades cardíacas antes de que se presenten síntomas',
    url: 'www.revistacientifica.com/articulo48',
    date: '2025-01-07',
  },
  {
    id: 39,
    title: 'Descubren una nueva especie de dinosaurio en el desierto de Gobi',
    description: 'Este dinosaurio, que vivió hace más de 70 millones de años, proporciona nuevas pistas sobre la evolución de los reptiles prehistóricos',
    url: 'www.revistacientifica.com/articulo49',
    date: '2025-01-08',
  },
  {
    id: 40,
    title: 'El papel de la epigenética en la prevención y tratamiento de enfermedades crónicas',
    description: 'Estudios recientes sugieren que los cambios epigenéticos pueden influir en el desarrollo de enfermedades como la diabetes y el cáncer',
    url: 'www.revistacientifica.com/articulo50',
    date: '2025-01-09',
  },
  {
    id: 41,
    title: 'Científicos desarrollan una nueva técnica para la regeneración de tejidos cardíacos dañados',
    description: 'Esta técnica utiliza células madre y biomateriales avanzados para reparar el tejido cardíaco después de un infarto',
    url: 'www.revistacientifica.com/articulo51',
    date: '2025-01-10',
  },
  {
    id: 42,
    title: 'El impacto de la contaminación del aire en el desarrollo cognitivo de los niños',
    description: 'Un estudio revela que la exposición a contaminantes del aire puede afectar negativamente el desarrollo cerebral en la infancia',
    url: 'www.revistacientifica.com/articulo52',
    date: '2025-01-11',
  },
  {
    id: 43,
    title: 'Nuevas terapias basadas en la microbiota intestinal muestran eficacia en el tratamiento de enfermedades autoinmunes',
    description: 'Estas terapias están diseñadas para restaurar el equilibrio de la flora intestinal y mejorar la salud del sistema inmunológico',
    url: 'www.revistacientifica.com/articulo53',
    date: '2025-01-12',
  },
  {
    id: 44,
    title: 'El uso de la inteligencia artificial en la identificación de patrones climáticos extremos',
    description: 'Algoritmos avanzados están ayudando a predecir eventos climáticos extremos con mayor precisión, permitiendo una mejor preparación y respuesta',
    url: 'www.revistacientifica.com/articulo54',
    date: '2025-01-13',
  },
  {
    id: 45,
    title: 'Descubren un nuevo método para la producción sostenible de hidrógeno',
    description: 'Este método utiliza energía solar para dividir el agua en hidrógeno y oxígeno, ofreciendo una fuente de energía limpia y renovable',
    url: 'www.revistacientifica.com/articulo55',
    date: '2025-01-14',
  },
  {
    id: 46,
    title: 'El impacto de los cambios en el uso de la tierra en la biodiversidad global',
    description: 'Un estudio global revela cómo la deforestación y la urbanización están afectando a diversas especies y ecosistemas',
    url: 'www.revistacientifica.com/articulo56',
    date: '2025-01-15',
  },
  {
    id: 47,
    title: 'Nuevas tecnologías para la detección temprana de enfermedades neurodegenerativas',
    description: 'Estas tecnologías están diseñadas para identificar biomarcadores específicos en las etapas iniciales de enfermedades como el Alzheimer',
    url: 'www.revistacientifica.com/articulo57',
    date: '2025-01-16',
  },
  {
    id: 48,
    title: 'El uso de la realidad aumentada en la educación: un enfoque innovador',
    description: 'La realidad aumentada está siendo utilizada para crear experiencias de aprendizaje inmersivas y mejorar la comprensión de conceptos complejos',
    url: 'www.revistacientifica.com/articulo58',
    date: '2025-01-17',
  },
  {
    id: 49,
    title: 'Descubren un nuevo compuesto químico que podría mejorar la eficiencia de las baterías de iones de litio',
    description: 'Este compuesto tiene el potencial de aumentar la capacidad y la vida útil de las baterías utilizadas en dispositivos electrónicos y vehículos eléctricos',
    url: 'www.revistacientifica.com/articulo59',
    date: '2025-01-18',
  },
  {
    id: 50,
    title: 'El papel de la genética en la resistencia a las enfermedades infecciosas',
    description: 'Investigadores han identificado genes específicos que podrían conferir resistencia a ciertas enfermedades infecciosas, abriendo nuevas vías para el desarrollo de tratamientos',
    url: 'www.revistacientifica.com/articulo60',
    date: '2025-01-19',
  },
  {
    id: 51,
    title: 'Científicos desarrollan una nueva técnica para la reparación de tejidos nerviosos dañados',
    description: 'Esta técnica utiliza nanomateriales y factores de crecimiento para promover la regeneración de nervios dañados, ofreciendo esperanza a pacientes con lesiones nerviosas',
    url: 'www.revistacientifica.com/articulo/61',
    date: '2025-01-20',
  },
  {
    id: 52,
    title: 'El impacto del cambio climático en la producción de alimentos: un estudio global',
    description: 'Investigadores han documentado cómo el calentamiento global está afectando la productividad agrícola y proponiendo soluciones para mitigar sus efectos',
    url: 'www.revistacientifica.com/articulo/62',
    date: '2025-01-21',
  },
  {
    id: 53,
    title: 'Nuevas terapias basadas en la edición genética muestran eficacia en el tratamiento de enfermedades raras',
    description: 'Estas terapias están diseñadas para corregir mutaciones genéticas específicas, ofreciendo esperanza a pacientes con enfermedades genéticas poco comunes',
    url: 'www.revistacientifica.com/articulo/63',
    date: '2025-01-22',
  },
  {
    id: 54,
    title: 'El uso de la inteligencia artificial en la optimización de procesos industriales',
    description: 'Algoritmos avanzados están siendo utilizados para mejorar la eficiencia y reducir los costos en diversas industrias, desde la manufactura hasta la energía',
    url: 'www.revistacientifica.com/articulo/64',
    date: '2025-01-23',
  },
  {
    id: 55,
    title: 'Descubren un nuevo compuesto químico que podría mejorar la eficiencia de los paneles solares',
    description: 'Este compuesto tiene el potencial de aumentar la capacidad de conversión de energía solar en electricidad, haciendo que los paneles solares sean más eficientes y rentables',
    url: 'www.revistacientifica.com/articulo/65',
    date: '2025-01-24',
  },
  {
    id: 56,
    title: 'El impacto de la contaminación del agua en la salud humana: un estudio alarmante',
    description: 'Investigaciones recientes han encontrado contaminantes peligrosos en fuentes de agua potable, lo que plantea serias preocupaciones sobre sus efectos a largo plazo en la salud',
    url: 'www.revistacientifica/articulo/66',
    date: '2025-01-25',
  },
  {
    id: 57,
    title: 'Nuevas tecnologías para la detección temprana de cáncer mediante análisis de imágenes',
    description: 'Estas tecnologías están diseñadas para identificar signos tempranos de cáncer en imágenes médicas, mejorando las tasas de detección y tratamiento',
    url: 'www.revistacientifica.com/articulo/67',
    date: '2025-01-26',
  },
  {
    id: 58,
    title: 'El uso de la realidad virtual en la terapia psicológica: un enfoque innovador',
    description: 'La realidad virtual está siendo utilizada para crear entornos controlados que ayudan a los pacientes a enfrentar y superar sus miedos y traumas',
    url: 'www.revistacientifica.com/articulo/68',
    date: '2025-01-27',
  },
  {
    id: 59,
    title: 'Descubren un nuevo compuesto químico que podría mejorar la eficiencia de las baterías de iones de litio',
    description: 'Este compuesto tiene el potencial de aumentar la capacidad y la vida útil de las baterías utilizadas en dispositivos electrónicos y vehículos eléctricos',
    url: 'www.revistacientifica.com/articulo/69',
    date: '2025-01-28',
  },
  {
    id: 60,
    title: 'El papel de la genética en la resistencia a las enfermedades infecciosas',
    description: 'Investigadores han identificado genes específicos que podrían conferir resistencia a ciertas enfermedades infecciosas, abriendo nuevas vías para el desarrollo de tratamientos',
    url: 'www.revistacientifica.com/articulo/70',
    date: '2025-01-29',
  },
]